const ch_str = {
	SALTZ: 'saltz',
	KRUBER: 'kruber',
	BARDIN: 'bardin',
	SIENNA: 'sienna',
	KERI: 'keri',
};

const cat_str = {
	CHARACTERS: 'chars',
	CLASSES: 'cls',
	WPN_MELEE: 'wpnm',
	WPN_RANGED: 'wpnr',
};

const cls_str = {
	SALTZ_WHC: 'saltz-whc-1',
	SALTZ_BH: 'saltz-bh-2',
	SALTZ_ZLT: 'saltz-zlt-3',
	KRUBER_MRC: 'kruber-mrc-1',
	KRUBER_HNT: 'kruber-hnt-2',
	KRUBER_FK: 'kruber-fk-3',
	BARDIN_RV: 'bardin-rv-1',
	BARDIN_IB: 'bardin-ib-2',
	BARDIN_SLR: 'bardin-slr-3',
	SIENNA_BW: 'sienna-bw-1',
	SIENNA_PR: 'sienna-pr-2',
	SIENNA_UNC: 'sienna-unc-3',
	KERI_WS: 'keri-ws-1',
	KERI_HM: 'keri-hm-2',
	KERI_SHD: 'keri-shd-3',
};

const wpnm_str = {
	SALTZ_AXE: 'saltz-axe-123',
	SALTZ_FLC: 'saltz-flc-123',
	SALTZ_FLAIL: 'saltz-flail-123',
	SALTZ_RPR: 'saltz-rpr-123',
	SALTZ_SWRD2H: 'saltz-swrd2h-123',
	SALTZ_AXENFLC: 'saltz-axenflc-123',
	SALTZ_BILLHK: 'saltz-billhk-123',
	KRUBER_EXEC: 'kruber-exec-123',
	KRUBER_HLB: 'kruber-hlb-123',
	KRUBER_MACE1H: 'kruber-mace1h-123',
	KRUBER_MACENSHLD: 'kruber-macenshld-123',
	KRUBER_SWRD1H: 'kruber-swrd1h-123',
	KRUBER_SWRDNSHLD: 'kruber-swrdnshld-123',
	KRUBER_HMMR2H: 'kruber-hmmr2h-123',
	KRUBER_SWRD2H: 'kruber-swrd2h-123',
	KRUBER_MACENSWRD: 'kruber-macenswrd-123',
	KRUBER_SPR: 'kruber-spr-12',
	BARDIN_AXE: 'bardin-axe-123',
	BARDIN_AXENSHLD: 'bardin-axenshld-12',
	BARDIN_AXEDUAL: 'bardin-axedual-3',
	BARDIN_AXE2H: 'bardin-axe2h-123',
	BARDIN_HMMR: 'bardin-hmmr-123',
	BARDIN_HMMRNSHLD: 'bardin-hmmrnshld-12',
	BARDIN_HMMR2H: 'bardin-hmmr2h-123',
	BARDIN_PICK: 'bardin-pick-123',
	BARDIN_HMMRDUAL: 'bardin-hmmrdual-123',
	SIENNA_DAG: 'sienna-dag-123',
	SIENNA_SWRDFIRE: 'sienna-swrdfire-123',
	SIENNA_MACE2H: 'sienna-mace2h-123',
	SIENNA_SWRD: 'sienna-swrd-123',
	SIENNA_CRWBILL: 'sienna-crwbill-123',
	SIENNA_FLAIL: 'sienna-flail-123',
	KERI_DAGDUAL: 'keri-dagdual-123',
	KERI_SWRDDUAL: 'keri-swrddual-123',
	KERI_SPR: 'keri-spr-123',
	KERI_GLV: 'keri-glv-123',
	KERI_SWRD: 'keri-swrd-123',
	KERI_SWRDNDAG: 'keri-swrdndag-123',
	KERI_SWRD2H: 'keri-swrd2h-123',
	KERI_AXE: 'keri-axe-123',
	KERI_SPRNSHLD: 'keri-sprnshld-2',
};

const wpnr_str = {
	SALTZ_BOP: 'saltz-bop-123',
	SALTZ_XBOW: 'saltz-xbow-123',
	SALTZ_RPTR: 'saltz-rptr-123',
	SALTZ_VXBOW: 'saltz-vxbow-123',
	KRUBER_BLNDR: 'kruber-blndr-123',
	KRUBER_HAND: 'kruber-hand-123',
	KRUBER_LBOW: 'kruber-lbow-2',
	KRUBER_RPTR: 'kruber-rptr-123',
	BARDIN_XBOW: 'bardin-xbow-12',
	BARDIN_DRKPSTL: 'bardin-drkpstl-2',
	BARDIN_DKRGUN: 'bardin-drkgun-2',
	BARDIN_GRUDGE: 'bardin-grudge-12',
	BARDIN_HAND: 'bardin-hand-12',
	BARDIN_TAXES: 'bardin-taxes-13',
	SIENNA_BEAM: 'sienna-beam-123',
	SIENNA_BOLT: 'sienna-bolt-123',
	SIENNA_CONF: 'sienna-conf-123',
	SIENNA_FIREBALL: 'sienna-fireball-123',
	SIENNA_FLAME: 'sienna-flame-123',
	KERI_HAG: 'keri-hag-123',
	KERI_LBOW: 'keri-lbow-123',
	KERI_SBOW: 'keri-sbow-123',
	KERI_VXBOW: 'keri-vxbow-3',
};

//localizing strings
res_chars = {
	[ch_str.SALTZ]: 'Victor Saltzpyre',
	[ch_str.KRUBER]: 'Markus Kruber',
	[ch_str.BARDIN]: 'Bardin Goreksson',
	[ch_str.SIENNA]: 'Sienna Fuegonasus',
	[ch_str.KERI]:'Kerillian',
};

res_cls = {
	[cls_str.SALTZ_WHC]: 'Witch Hunter Captain',
	[cls_str.SALTZ_BH]: 'Bounty Hunter',
	[cls_str.SALTZ_ZLT]: 'Zealot',
	[cls_str.KRUBER_MRC]: 'Mercenary',
	[cls_str.KRUBER_HNT]: 'Huntsman',
	[cls_str.KRUBER_FK]: 'Foot Knight',
	[cls_str.BARDIN_RV]: 'Ranger Veteran',
	[cls_str.BARDIN_IB]: 'Ironbreaker',
	[cls_str.BARDIN_SLR]: 'Slayer',
	[cls_str.SIENNA_BW]: 'Battle Wizard',
	[cls_str.SIENNA_PR]: 'Pyromancer',
	[cls_str.SIENNA_UNC]: 'Unchained',
	[cls_str.KERI_WS]: 'Waystalker',
	[cls_str.KERI_HM]: 'Handmaiden',
	[cls_str.KERI_SHD]: 'Shade',
};

res_wpnm = {
	[wpnm_str.SALTZ_AXE]: 'Axe',
	[wpnm_str.SALTZ_FLC]: 'Falchion',
	[wpnm_str.SALTZ_FLAIL]: 'Flail',
	[wpnm_str.SALTZ_RPR]: 'Rapier',
	[wpnm_str.SALTZ_SWRD2H]: 'Greatsword',
	[wpnm_str.SALTZ_AXENFLC]: 'Axe & Falchion',
	[wpnm_str.SALTZ_BILLHK]: 'Bill Hook',
	[wpnm_str.KRUBER_EXEC]: 'Executioner Sword',
	[wpnm_str.KRUBER_HLB]: 'Halberd',
	[wpnm_str.KRUBER_MACE1H]: 'Mace',
	[wpnm_str.KRUBER_MACENSHLD]: 'Mace & Shield',
	[wpnm_str.KRUBER_SWRD1H]: 'Sword',
	[wpnm_str.KRUBER_SWRDNSHLD]: 'Sword & Shield',
	[wpnm_str.KRUBER_HMMR2H]: 'Great Hammer',
	[wpnm_str.KRUBER_SWRD2H]: 'Greatsword',
	[wpnm_str.KRUBER_MACENSWRD]: 'Mace & Sword',
	[wpnm_str.KRUBER_SPR]: 'Tuskgor Spear',
	[wpnm_str.BARDIN_AXE]: 'Axe',
	[wpnm_str.BARDIN_AXENSHLD]: 'Axe & Shield',
	[wpnm_str.BARDIN_AXEDUAL]: 'Dual Axes',
	[wpnm_str.BARDIN_AXE2H]: 'Great Axe',
	[wpnm_str.BARDIN_HMMR]: 'Hammer',
	[wpnm_str.BARDIN_HMMRNSHLD]: 'Hammer & Shield',
	[wpnm_str.BARDIN_HMMR2H]: 'Great Hammer',
	[wpnm_str.BARDIN_PICK]: 'War Pick',
	[wpnm_str.BARDIN_HMMRDUAL]: 'Dual Hammers',
	[wpnm_str.SIENNA_DAG]: 'Dagger',
	[wpnm_str.SIENNA_SWRDFIRE]: 'Fire Sword',
	[wpnm_str.SIENNA_MACE2H]: 'Mace',
	[wpnm_str.SIENNA_SWRD]: 'Sword',
	[wpnm_str.SIENNA_CRWBILL]: 'Crowbill',
	[wpnm_str.SIENNA_FLAIL]: 'Flaming Flail',
	[wpnm_str.KERI_DAGDUAL]: 'Dual Daggers',
	[wpnm_str.KERI_SWRDDUAL]: 'Dual Swords',
	[wpnm_str.KERI_SPR]: 'Elven Spear',
	[wpnm_str.KERI_GLV]: 'Glaive',
	[wpnm_str.KERI_SWRD]: 'Sword',
	[wpnm_str.KERI_SWRDNDAG]: 'Sword & Dagger',
	[wpnm_str.KERI_SWRD2H]: 'Greatsword',
	[wpnm_str.KERI_AXE]: 'Elven Axe',
	[wpnm_str.KERI_SPRNSHLD]: 'Spear & Shield',
};

res_wpnr = {
	[wpnr_str.SALTZ_BOP]: 'Brace of Pistols',
	[wpnr_str.SALTZ_XBOW]: 'Crossbow',
	[wpnr_str.SALTZ_RPTR]: 'Repeater Pistol',
	[wpnr_str.SALTZ_VXBOW]: 'Volley Crossbow',
	[wpnr_str.KRUBER_BLNDR]: 'Blunderbuss',
	[wpnr_str.KRUBER_HAND]: 'Handgun',
	[wpnr_str.KRUBER_LBOW]: 'Longbow',
	[wpnr_str.KRUBER_RPTR]: 'Repeater Handgun',
	[wpnr_str.BARDIN_XBOW]: 'Crossbow',
	[wpnr_str.BARDIN_DRKPSTL]: 'Drakefire Pistols',
	[wpnr_str.BARDIN_DKRGUN]: 'Drakegun',
	[wpnr_str.BARDIN_GRUDGE]: 'Grudge-Raker',
	[wpnr_str.BARDIN_HAND]: 'Handgun',
	[wpnr_str.BARDIN_TAXES]: 'Throwing Axes',
	[wpnr_str.SIENNA_BEAM]: 'Beam Staff',
	[wpnr_str.SIENNA_BOLT]: 'Bolt Staff',
	[wpnr_str.SIENNA_CONF]: 'Conflagration Staff',
	[wpnr_str.SIENNA_FIREBALL]: 'Fireball Staff',
	[wpnr_str.SIENNA_FLAME]: 'Flamestorm Staff',
	[wpnr_str.KERI_HAG]: 'Hagbane Shortbow',
	[wpnr_str.KERI_LBOW]: 'Longbow',
	[wpnr_str.KERI_SBOW]: 'Swift Bow',
	[wpnr_str.KERI_VXBOW]: 'Volley Crossbow',
};