const ch_str = {
	SALTZ: 'saltz',
	KRUBER: 'kruber',
	BARDIN: 'bardin',
	SIENNA: 'sienna',
	KERI: 'keri',
};

const cat_str = {
	CHARACTERS: 'chars',
	CLASSES: 'cls',
	WPN_MELEE: 'wpnm',
	WPN_RANGED: 'wpnr',
};

const cls_str = {
	SALTZ_WHC: 'saltz-whc-1',
	SALTZ_BH: 'saltz-bh-2',
	SALTZ_ZLT: 'saltz-zlt-3',
	KRUBER_MRC: 'kruber-mrc-1',
	KRUBER_HNT: 'kruber-hnt-2',
	KRUBER_FK: 'kruber-fk-3',
	BARDIN_RV: 'bardin-rv-1',
	BARDIN_IB: 'bardin-ib-2',
	BARDIN_SLR: 'bardin-slr-3',
	SIENNA_BW: 'sienna-bw-1',
	SIENNA_PR: 'sienna-pr-2',
	SIENNA_UNC: 'sienna-unc-3',
	KERI_WS: 'keri-ws-1',
	KERI_HM: 'keri-hm-2',
	KERI_SHD: 'keri-shd-3',
};

const wpnm_str = {
	SALTZ_AXE: 'saltz-axe-123',
	SALTZ_FLC: 'saltz-flc-123',
	SALTZ_FLAIL: 'saltz-flail-123',
	SALTZ_RPR: 'saltz-rpr-123',
	SALTZ_SWRD2H: 'saltz-swrd2h-123',
	SALTZ_AXENFLC: 'saltz-axenflc-123',
	SALTZ_BILLHK: 'saltz-billhk-123',
	KRUBER_EXEC: 'kruber-exec-123',
	KRUBER_HLB: 'kruber-hlb-123',
	KRUBER_MACE1H: 'kruber-mace1h-123',
	KRUBER_MACENSHLD: 'kruber-macenshld-123',
	KRUBER_SWRD1H: 'kruber-swrd1h-123',
	KRUBER_SWRDNSHLD: 'kruber-swrdnshld-123',
	KRUBER_HMMR2H: 'kruber-hmmr2h-123',
	KRUBER_SWRD2H: 'kruber-swrd2h-123',
	KRUBER_MACENSWRD: 'kruber-macenswrd-123',
	KRUBER_SPR: 'kruber-spr-12',
	BARDIN_AXE: 'bardin-axe-123',
	BARDIN_AXENSHLD: 'bardin-axenshld-12',
	BARDIN_AXEDUAL: 'bardin-axedual-3',
	BARDIN_AXE2H: 'bardin-axe2h-123',
	BARDIN_HMMR: 'bardin-hmmr-123',
	BARDIN_HMMRNSHLD: 'bardin-hmmrnshld-12',
	BARDIN_HMMR2H: 'bardin-hmmr2h-123',
	BARDIN_PICK: 'bardin-pick-123',
	BARDIN_HMMRDUAL: 'bardin-hmmrdual-123',
	SIENNA_DAG: 'sienna-dag-123',
	SIENNA_SWRDFIRE: 'sienna-swrdfire-123',
	SIENNA_MACE2H: 'sienna-mace2h-123',
	SIENNA_SWRD: 'sienna-swrd-123',
	SIENNA_CRWBILL: 'sienna-crwbill-123',
	SIENNA_FLAIL: 'sienna-flail-123',
	KERI_DAGDUAL: 'keri-dagdual-123',
	KERI_SWRDDUAL: 'keri-swrddual-123',
	KERI_SPR: 'keri-spr-123',
	KERI_GLV: 'keri-glv-123',
	KERI_SWRD: 'keri-swrd-123',
	KERI_SWRDNDAG: 'keri-swrdndag-123',
	KERI_SWRD2H: 'keri-swrd2h-123',
	KERI_AXE: 'keri-axe-123',
	KERI_SPRNSHLD: 'keri-sprnshld-2',
};

const wpnr_str = {
	SALTZ_BOP: 'saltz-bop-123',
	SALTZ_XBOW: 'saltz-xbow-123',
	SALTZ_RPTR: 'saltz-rptr-123',
	SALTZ_VXBOW: 'saltz-vxbow-123',
	KRUBER_BLNDR: 'kruber-blndr-123',
	KRUBER_HAND: 'kruber-hand-123',
	KRUBER_LBOW: 'kruber-lbow-2',
	KRUBER_RPTR: 'kruber-rptr-123',
	BARDIN_XBOW: 'bardin-xbow-12',
	BARDIN_DRKPSTL: 'bardin-drkpstl-2',
	BARDIN_DKRGUN: 'bardin-drkgun-2',
	BARDIN_GRUDGE: 'bardin-grudge-12',
	BARDIN_HAND: 'bardin-hand-12',
	BARDIN_TAXES: 'bardin-taxes-13',
	SIENNA_BEAM: 'sienna-beam-123',
	SIENNA_BOLT: 'sienna-bolt-123',
	SIENNA_CONF: 'sienna-conf-123',
	SIENNA_FIREBALL: 'sienna-fireball-123',
	SIENNA_FLAME: 'sienna-flame-123',
	KERI_HAG: 'keri-hag-123',
	KERI_LBOW: 'keri-lbow-123',
	KERI_SBOW: 'keri-sbow-123',
	KERI_VXBOW: 'keri-vxbow-3',
};

chars = {
	'all': {
		'name': 'ALL',
	},
	'saltz': {
		'name': 'Victor Saltzpyre',
	},
	'kruber': {
		'name': 'Markus Kruber',
	},
	'bardin': {
		'name': 'Bardin Goreksson',
	},
	'sienna': {
		'name': 'Sienna Fuegonasus',
	},
	'keri': {
		'name': 'Kerillian',
	},
};
